apiVersion: apps/v1
kind: DaemonSet
metadata:
  annotations:
    deprecated.daemonset.template.generation: "3"
    kubectl.kubernetes.io/last-applied-configuration: |
      {"apiVersion":"apps/v1","kind":"DaemonSet","metadata":{"annotations":{},"labels":{"k8s-app":"fluent-bit"},"name":"fluent-bit","namespace":"amazon-cloudwatch"},"spec":{"selector":{"matchLabels":{"k8s-app":"fluent-bit"}},"template":{"metadata":{"labels":{"k8s-app":"fluent-bit"}},"spec":{"containers":[{"env":[{"name":"AWS_REGION","value":"ap-south-1"},{"name":"CLUSTER_NAME","value":"brain-tasks-cluster"},{"name":"READ_FROM_HEAD","value":"Off"},{"name":"READ_FROM_TAIL","value":"On"}],"image":"public.ecr.aws/aws-observability/aws-for-fluent-bit:latest","name":"fluent-bit","resources":{"limits":{"memory":"200Mi"},"requests":{"cpu":"100m","memory":"100Mi"}},"volumeMounts":[{"mountPath":"/var/lib/docker/containers","name":"varlibdockercontainers","readOnly":true},{"mountPath":"/var/log","name":"varlog","readOnly":true},{"mountPath":"/fluent-bit/etc/","name":"config"}]}],"serviceAccountName":"fluent-bit","terminationGracePeriodSeconds":10,"volumes":[{"hostPath":{"path":"/var/lib/docker/containers"},"name":"varlibdockercontainers"},{"hostPath":{"path":"/var/log"},"name":"varlog"}]}}}}
  creationTimestamp: "2025-10-31T10:45:12Z"
  generation: 3
  labels:
    k8s-app: fluent-bit
  name: fluent-bit
  namespace: amazon-cloudwatch
  resourceVersion: "398529"
  uid: 5bf25231-ba21-4b00-9bc1-94ffbd2684e3
spec:
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      k8s-app: fluent-bit
  template:
    metadata:
      annotations:
        kubectl.kubernetes.io/restartedAt: "2025-10-31T17:22:26+05:30"
      creationTimestamp: null
      labels:
        k8s-app: fluent-bit
    spec:
      containers:
      - env:
        - name: AWS_REGION
          value: ap-south-1
        - name: CLUSTER_NAME
          value: brain-tasks-cluster
        - name: READ_FROM_HEAD
          value: "Off"
        - name: READ_FROM_TAIL
          value: "On"
        image: public.ecr.aws/aws-observability/aws-for-fluent-bit:latest
        imagePullPolicy: Always
        name: fluent-bit
        resources:
          limits:
            memory: 200Mi
          requests:
            cpu: 100m
            memory: 100Mi
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
        volumeMounts:
        - mountPath: /var/lib/docker/containers
          name: varlibdockercontainers
          readOnly: true
        - mountPath: /var/log
          name: varlog
          readOnly: true
        - mountPath: /fluent-bit/etc/
          name: config
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      serviceAccount: fluent-bit
      serviceAccountName: fluent-bit
      terminationGracePeriodSeconds: 10
      volumes:
      - hostPath:
          path: /var/lib/docker/containers
          type: ""
        name: varlibdockercontainers
      - hostPath:
          path: /var/log
          type: ""
        name: varlog
      - name: config
        configMap:
          name: fluent-bit-config
  updateStrategy:
    rollingUpdate:
      maxSurge: 0
      maxUnavailable: 1
    type: RollingUpdate
status:
  currentNumberScheduled: 2
  desiredNumberScheduled: 2
  numberAvailable: 2
  numberMisscheduled: 0
  numberReady: 2
  observedGeneration: 3
  updatedNumberScheduled: 2
